import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';

class AppImages {
  static const String logo = 'assets/logo.svg';
  static const String landingImage = 'assets/landingImage.png';
  static const String smartLuxury = 'assets/smartLuxury.svg';
  static const String googleIcon = 'assets/googleIcon.svg';
  static const String emailIcon = 'assets/emailIcon.svg';
  static const String mobileIcon = 'assets/mobileIcon.svg';
  static const String appLogo = 'assets/appLogo.svg';
  static const String logoWhite = 'assets/logoWhite.svg';
  static const String IOTIQ_UtilityText = 'assets/IOTIQ_Utility.svg';
  static const String devicesIcon = 'assets/devices.svg';
  static const String setupIcon = 'assets/setup.svg';
  static const String setup = 'assets/setUpIcon.svg';
  static const String setupDetails = 'assets/setupDetails.svg';
  static const String usageIcon = 'assets/usage.svg';
  static const String appLogoOrange = 'assets/appLogoOrange.svg';
  static const String profileIcon = 'assets/drawerIcons/profileIcon.svg';
  static const String learnnIcon = 'assets/drawerIcons/learnIcon.svg';
  static const String spaces = 'assets/drawerIcons/spaces.svg';
  static const String buyIcon = 'assets/drawerIcons/buyIcon.svg';
  static const String devicesDrawer = 'assets/drawerIcons/devicesDrawer.svg';
  static const String notification = 'assets/drawerIcons/notification.svg';
  static const String support = 'assets/drawerIcons/support.svg';
  static const String ripples = 'assets/ripples.svg';
  static const String checkIcon = 'assets/check.png';
  static const String seedling = 'assets/seedling.png';
  static const String increaseDecrease = 'assets/increaseDecrease.svg';
  static const String backgroundImageUsage = 'assets/backgroundImageUsage.svg';
  static const String electricMotor = 'assets/base.png';
  static const String waterTapPng = 'assets/waterTank.png';
  static const String naturalGas = 'assets/naturalGas.png';
  static const String vector = 'assets/vector.svg';
  static const String homeEmptyScreen = 'assets/homeEmptyScreen.png';
  static const String deviceSetup = 'assets/deviceSetup.svg';
  static const String waterTank = 'assets/waterFill.png';
  static const String motor = 'assets/base.png';
  static const String splashImage = 'assets/splashLottie.json';
  static const String loaderLottie = 'assets/loaderLottie.json';
  static const String mainLoading = 'assets/mainLoading.json';
  static const String waterTankLottie = 'assets/waterTankLottie.json';
  static const String loading = 'assets/loading.json';
}

SizedBox height5 = SizedBox(height: 5.h);
SizedBox height8 = SizedBox(height: 8.h);
SizedBox height10 = SizedBox(height: 10.h);
SizedBox height15 = SizedBox(height: 15.h);
SizedBox height20 = SizedBox(height: 20.h);
SizedBox height30 = SizedBox(height: 30.h);
SizedBox height40 = SizedBox(height: 40.h);
SizedBox height50 = SizedBox(height: 50.h);
SizedBox height60 = SizedBox(height: 60.h);
SizedBox height70 = SizedBox(height: 70.h);
SizedBox width5 = SizedBox(width: 5.w);
SizedBox width10 = SizedBox(width: 10.w);
SizedBox width15 = SizedBox(width: 15.w);
SizedBox width20 = SizedBox(width: 20.w);
SizedBox width30 = SizedBox(width: 30.w);
SizedBox width40 = SizedBox(width: 40.w);
SizedBox width50 = SizedBox(width: 50.w);
SizedBox width55 = SizedBox(width: 55.w);
SizedBox width60 = SizedBox(width: 60.w);
